name: Run icon font build on PR to main

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    uses: ./.github/workflows/icon-sync-glyphs.yml
    with:
      config-directory: builders/glyphs
